-- JR Media - initial database schema
create table if not exists public.media (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null check (type in ('film','serie','cartoon')),
  year integer,
  genre text,
  description text,
  poster_url text,
  video_url text,
  download_url text,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  media_id bigint not null references public.media(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, media_id)
);

alter table public.media enable row level security;
alter table public.favorites enable row level security;

create policy "Anyone can read media" on public.media
for select using (true);

create policy "Users can read their favorites" on public.favorites
for select to authenticated using (auth.uid() = user_id);

create policy "Users can add their favorites" on public.favorites
for insert to authenticated with check (auth.uid() = user_id);

create policy "Users can delete their favorites" on public.favorites
for delete to authenticated using (auth.uid() = user_id);

-- Demo metadata only. Replace/remove these entries before production.
insert into public.media (title,type,year,genre,description,featured)
values
('Voyage des étoiles','film',2026,'Science-fiction','Contenu de démonstration JR Media.',true),
('Mystère à Minuit','film',2025,'Mystère','Contenu de démonstration JR Media.',true),
('Les Explorateurs','serie',2026,'Aventure','Contenu de démonstration JR Media.',true),
('Planète Junior','cartoon',2025,'Animation','Contenu de démonstration JR Media.',false)
on conflict do nothing;
